# Generated by Django 4.0.3 on 2022-03-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия, Имя, Отчество')),
                ('mobile_phone', models.CharField(blank=True, max_length=100, verbose_name='Сотовый или городской телефон')),
                ('internal_phone', models.CharField(blank=True, max_length=100, verbose_name='Внутренний телефон')),
                ('IP_phone', models.CharField(blank=True, max_length=100, verbose_name='IP телефон')),
                ('pts_phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон ПТС')),
                ('conference_phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон конференц-связи')),
                ('zas_phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон ЗАС')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
            },
        ),
    ]
