# Generated by Django 4.0.3 on 2022-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_abonent_options_abonent_gorod_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Фамилия, Имя, Отчество'),
        ),
    ]
