# Generated by Django 4.0.3 on 2022-04-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_alter_abonent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonent',
            name='zvks',
            field=models.CharField(blank=True, max_length=100, verbose_name='ЗВКС'),
        ),
    ]
